modLoader="javafml"
loaderVersion="[39,)"
issueTrackerURL="https://github.com/Mrbysco/AgeingSpawners"
license="MIT"

[[mods]]
modId="ageingspawners"
version="${file.jarVersion}"
displayName="Ageing Spawners"
displayURL="https://www.curseforge.com/minecraft/mc-mods/ageing-spawners"
authors="Mrbysco, ShyNieke"
description='''
Spawners that have a limit
'''
[[dependencies.ageingspawners]]
modId="minecraft"
mandatory=true
versionRange="[1.18.1,1.19)"
ordering="NONE"
side="BOTH"