modLoader="javafml"
loaderVersion="[2,)"
issueTrackerURL="https://github.com/Mrbysco/AgeingSpawners/issues"
license="MIT"

[[mods]]
modId="ageingspawners"
version="${file.jarVersion}"
displayName="Ageing Spawners"
displayURL="https://www.curseforge.com/minecraft/mc-mods/ageing-spawners"
authors="Mrbysco, ShyNieke"
description='''
Spawners that have a limit
'''
[[dependencies.ageingspawners]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.20.4,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.ageingspawners]]
modId="neoforge"
type="REQUIRED"
versionRange="[20.4.70-beta,)"
ordering="NONE"
side="BOTH"
[[mixins]]
config = "ageingspawners.mixins.json"