modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/Mrbysco/AgeingSpawners"

[[mods]]
modId="ageingspawners"
version="${file.jarVersion}"
displayName="Ageing Spawners"
displayURL="https://www.curseforge.com/minecraft/mc-mods/ageing-spawners"
authors="Mrbysco, ShyNieke"
description='''
Spawners that have a limit
'''